name: Regression End-to-end tests
# burada hangi durumda run olmasını istiyorsak onu ekliyoruz. Mesela aşağıda push olduğunda
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

# SLACK NOTIFICATION IS BELOW ==============================

      - name: Slack Notification
        #It will work also in case of failed. if: always ()
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Test Automation Ran: https://github.com/CumaliORUC/Cypress-POM-WithReports/actions/runs/{{github.run_id}}'
          SLACK_TITLE: Cypress Web Test
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}