name: Parallel Run (Register and Add to Cart Flows)
# burada hangi durumda run olmasını istiyorsak onu ekliyoruz. Mesela aşağıda push olduğunda
on: push
jobs:
  Add-to-Cart-Flow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
   
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
           command: npm run test:addToCart
  
   # burada ismini değiştirebilirisin.
  RegisterFlow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
           command: npm run test:registerFlow